# Generated by Django 4.0.4 on 2022-05-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collect',
            options={'ordering': ['-created_at'], 'verbose_name': 'Идея', 'verbose_name_plural': 'Идеи'},
        ),
        migrations.AlterField(
            model_name='collect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание текущей ситуации (недостатки)'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='offer',
            field=models.TextField(blank=True, verbose_name='Предложение по улучшению'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='result',
            field=models.TextField(blank=True, verbose_name='Ожидаемый результат'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Наименование идеи'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
