# Generated by Django 4.0.4 on 2022-06-06 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_category_collect_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='collect.category', verbose_name='Наименование категории эффекта'),
            preserve_default=False,
        ),
    ]
