# Generated by Django 4.0.4 on 2022-07-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0004_alter_collect_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
